#include <iostream>
using namespace std;

int isInAnchorSet(char * nonTerminal, int tokenType);
void errorhandler(char *, int);
void trace(char *);
void program(FILE *);
void type_specifier(FILE *);
void param_decl_list(FILE *);
void param_decl(FILE *);
void compound_st(FILE *);
void compound_st_tail(FILE *);
void var_decl(FILE *);
void var_decl_list(FILE *);
void variable_ident(FILE *);
void variable_ident_t(FILE *);
void statement(FILE *);
void conditional_st(FILE *);
void if_tail(FILE *);
void while_st(FILE *);  
void expression_st(FILE *);
void condition(FILE *);
void condition_tail(FILE *);
void disjunction(FILE *);
void disjunction_prime(FILE *);
void conjunction(FILE *);
void conjunction_prime(FILE *);
void comparison(FILE *);
void comparison_tail(FILE *);
void relation(FILE *);
void relation_tail(FILE *);
void sum(FILE *);
void sum_prime(FILE *);
void term(FILE *);
void term_prime(FILE *);
void factor(FILE *);
void primary(FILE *);
void identifier(FILE *);
void integer_num(FILE *);
void float_num(FILE *);	